# Introduction to numpy

In [13]:
import numpy as np

In [14]:
data= np.random.randn(2,3)

In [15]:
data

array([[ 0.43084119, -0.35062099,  0.87006032],
       [ 0.93962155,  0.13977085, -0.81696544]])

## Shape of the data

In [16]:
data.shape

(2, 3)

In [17]:
data.dtype

dtype('float64')

In [18]:
##Pythonic list 

In [19]:
data1 = [6,7.5,7,8,9,1]

In [20]:
print(type(data1))

<class 'list'>


In [21]:
arr1=np.array(data1)

In [22]:
type(arr1)

numpy.ndarray

In [23]:
data2=[[1,2,3,4],[5,6,7,8]]

In [24]:
arr2=np.array(data2)

In [25]:
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [26]:
arr2.ndim

2

In [27]:
arr2.shape

(2, 4)

In [28]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Arrange = a + range

it is similar to python's built in range method <br>
for (int i = start, i < stop, i = i + step)

np.arrange(start,stop,step)

In [29]:
np.arange(3,10,1).ndim

1

#### The default value of start is 0,  and step =1, it wouldn't include the last index element

In [30]:
for i in range(4,5,1):
    print(i)

4


In [31]:
np.arange(3,-10,-3)

array([ 3,  0, -3, -6, -9])

In [32]:
arr1=np.array([1,2,3,4,5],dtype=np.float64)

In [33]:
print(arr1)

[1. 2. 3. 4. 5.]


In [34]:
arr1.dtype

dtype('float64')

## Typecasting numpy array

In [35]:
arrr=np.array([1,2,3,4,5])

In [36]:
print(arrr)

[1 2 3 4 5]


In [37]:
arrr.dtype

dtype('int64')

In [38]:
arrr.astype(np.float64)

array([1., 2., 3., 4., 5.])

In [39]:
data2=np.array([[1,2,3,4],[5,6,7,8]])

In [40]:
print(data2)

[[1 2 3 4]
 [5 6 7 8]]


In [41]:
data2+data2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [42]:
data2*data2

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [43]:
dp=np.arange(10)

In [44]:
dp[3]

3

In [45]:
dp[5:8]

array([5, 6, 7])

In [46]:
dp[5:8]=12

In [47]:
dp

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

## Two dimensional Array

In [48]:
arr2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [49]:
print(arr2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [50]:
print(arr2d[2])

[ 9 10 11 12]


In [51]:
print(arr2d[0][2])

3


In [52]:
print(arr2d[0,2]) #either way is fine 

3


## Pandas

In [53]:
import pandas as pd

In [ ]:
###it can handle hetrogeneous data


In [56]:
obj=pd.Series([4,7,-5,3])

In [57]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [58]:
obj.values

array([ 4,  7, -5,  3])

In [59]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [60]:
obj2 = pd.Series([4,7,-5,3]), index=['a','b','c','d']

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (3989998973.py, line 1)